```{r}

library(ggplot2)
library(tidyverse)
library(here)

```

```{r}
stroke_patients <- read_csv(here("data/healthcare-dataset-stroke-data.csv"))

```

```{r}
  


ggplot(data = stroke_patients, aes(x=factor(hypertension), fill = factor(stroke))) + 
  geom_bar(position = "dodge") +
  labs(fill = "stroke")
```

P(B) 
```{r}
stroke_patients |> 
  count(stroke) |> 
  mutate(percent = n / sum(n))

probability_stroke <- stroke_patients %>% 
  count(stroke) %>% 
  mutate(percent = n / sum(n)) %>% 
  filter(stroke == 1) %>% 
  pull(percent)
```

P(A|B)
```{r}
stroke_patients |> 
  count(stroke, hypertension) |> 
  group_by(stroke) |> 
  mutate(percent = n / sum(n))

probability_hypertension_result_given_stroke <- stroke_patients %>% 
  count(stroke, hypertension) %>% 
  group_by(stroke) %>% 
  mutate(percent = n / sum(n)) %>% 
  filter(stroke == 1, hypertension == 1) %>% 
  pull(percent)

```
P(A)
```{r}
stroke_patients |> 
  count(hypertension) |> 
  mutate(percent = n / sum(n))

probability_hypertension <- stroke_patients %>% 
  count(hypertension) %>% 
  mutate(percent = n / sum(n)) %>% 
  filter(hypertension == 1) %>% 
  pull(percent)
```
```{r}
(probability_hypertension_result_given_stroke * probability_stroke) / probability_hypertension

```

